# Generated by Django 4.2 on 2023-04-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('document_numbre', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('leader', models.CharField(default='SYSTEM', max_length=4)),
                ('address', models.CharField(max_length=150)),
                ('commune', models.CharField(max_length=150)),
                ('neighborhood', models.CharField(max_length=150)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
    ]
