# Generated by Django 4.2 on 2023-05-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_commune', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('document_number', models.CharField(error_messages={'unique': 'Documento ya ha sido registrado'}, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('document_number', models.CharField(error_messages={'unique': 'Documento ya ha sido registrado'}, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('commune', models.CharField(max_length=150)),
                ('neighborhood', models.CharField(max_length=150)),
                ('is_valid', models.BooleanField(default=False)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_user.userleader')),
            ],
        ),
        migrations.CreateModel(
            name='NeighborhoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_neighborhood', models.CharField(max_length=150, unique=True)),
                ('name_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_user.communemodel')),
            ],
        ),
    ]
