# Generated by Django 4.2 on 2023-05-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleader',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='document_number',
            field=models.CharField(error_messages={'unique': 'Documento está registrado'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
