# Generated by Django 4.2 on 2023-05-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_user', '0002_alter_userleader_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleader',
            name='email',
            field=models.EmailField(blank=True, default='mysite@mydominio.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='mysite@mydominio.com', max_length=254, null=True),
        ),
    ]
