# Generated by Django 4.2 on 2023-04-18 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_user', '0002_rename_form_user_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='document_numbre',
            new_name='document_number',
        ),
    ]
