# Generated by Django 4.2 on 2023-05-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_user', '0003_alter_userleader_email_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleader',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
