# Generated by Django 4.2 on 2023-04-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_user', '0003_rename_document_numbre_userprofile_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='document_number',
            field=models.CharField(error_messages={'unique': 'Documento ya ha sido registrado'}, max_length=50, unique=True),
        ),
    ]
