# Generated by Django 4.2 on 2023-05-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_user', '0005_communemodel_userleader_neighborhoodmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communemodel',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
